const WineData = [
  {
    id: 1,
    name: "Prosecco Extra Dry",
    brand: "La Marca",
    type: "Sparkling",
    color: "Sparkling",
    grapeOrigin: "Italy",
    sweetness: "Dry",
    locationPurchased: "Binny's",
    price: 18.99,
    year: 2022,
    labelPhoto: "",
    dateAdded: "2025-03-05T12:00:00Z",
    tastings: [],
  },
  {
    id: 2,
    name: "Sonoma Chardonnay",
    brand: "Sonoma Vineyards",
    type: "White",
    color: "White",
    grapeOrigin: "California",
    sweetness: "Dry",
    locationPurchased: "Total Wine",
    price: 15.5,
    year: 2021,
    labelPhoto: "",
    dateAdded: "2025-03-07T15:00:00Z",
    tastings: [],
  },
  {
    id: 3,
    name: "Provence Rosé",
    brand: "Whispering Angel",
    type: "Rosé",
    color: "Rosé",
    grapeOrigin: "France",
    sweetness: "Dry",
    locationPurchased: "Whole Foods",
    price: 22.0,
    year: 2023,
    labelPhoto: "",
    dateAdded: "2025-03-08T11:30:00Z",
    tastings: [],
  },
  {
    id: 4,
    name: "Napa Cabernet Sauvignon",
    brand: "Silver Oak",
    type: "Red",
    color: "Red",
    grapeOrigin: "California",
    sweetness: "Dry",
    locationPurchased: "Binny's",
    price: 45.0,
    year: 2020,
    labelPhoto: "",
    dateAdded: "2025-03-09T09:45:00Z",
    tastings: [],
  },
  {
    id: 5,
    name: "Moscato d'Asti",
    brand: "Saracco",
    type: "Dessert",
    color: "Dessert",
    grapeOrigin: "Italy",
    sweetness: "Sweet",
    locationPurchased: "Trader Joe's",
    price: 13.99,
    year: 2022,
    labelPhoto: "",
    dateAdded: "2025-03-10T17:15:00Z",
    tastings: [],
  },
  {
    id: 6,
    name: "Pinot Noir",
    brand: "La Crema",
    type: "Red",
    color: "Red",
    grapeOrigin: "California",
    sweetness: "Dry",
    locationPurchased: "Whole Foods",
    price: 21.99,
    year: 2020,
    labelPhoto: "",
    dateAdded: "2025-03-11T14:30:00Z",
    tastings: [],
  },
  {
    id: 7,
    name: "Chardonnay",
    brand: "Kendall-Jackson",
    type: "White",
    color: "White",
    grapeOrigin: "California",
    sweetness: "Dry",
    locationPurchased: "Costco",
    price: 12.99,
    year: 2021,
    labelPhoto: "",
    dateAdded: "2025-03-12T11:00:00Z",
    tastings: [],
  },
  {
    id: 8,
    name: "Rosé",
    brand: "Whispering Angel",
    type: "Rosé",
    color: "Rosé",
    grapeOrigin: "France",
    sweetness: "Dry",
    locationPurchased: "Binny's",
    price: 18.99,
    year: 2023,
    labelPhoto: "",
    dateAdded: "2025-03-13T15:45:00Z",
    tastings: [],
  },
  {
    id: 9,
    name: "Prosecco",
    brand: "La Marca",
    type: "Sparkling",
    color: "Sparkling",
    grapeOrigin: "Italy",
    sweetness: "Semi-Sweet",
    locationPurchased: "Target",
    price: 15.99,
    year: 2022,
    labelPhoto: "",
    dateAdded: "2025-03-14T12:20:00Z",
    tastings: [],
  },
  {
    id: 10,
    name: "Riesling",
    brand: "Dr. Loosen",
    type: "White",
    color: "White",
    grapeOrigin: "Germany",
    sweetness: "Semi-Sweet",
    locationPurchased: "Trader Joe's",
    price: 14.99,
    year: 2022,
    labelPhoto: "",
    dateAdded: "2025-03-15T09:10:00Z",
    tastings: [],
  },
  {
    id: 11,
    name: "Sauvignon Blanc",
    brand: "Kim Crawford",
    type: "White",
    color: "White",
    grapeOrigin: "New Zealand",
    sweetness: "Dry",
    locationPurchased: "Costco",
    price: 16.99,
    year: 2023,
    labelPhoto: "",
    dateAdded: "2025-03-16T16:25:00Z",
    tastings: [],
  },
  {
    id: 12,
    name: "Merlot",
    brand: "Duckhorn",
    type: "Red",
    color: "Red",
    grapeOrigin: "California",
    sweetness: "Dry",
    locationPurchased: "Whole Foods",
    price: 24.99,
    year: 2019,
    labelPhoto: "",
    dateAdded: "2025-03-17T10:05:00Z",
    tastings: [],
  },
  {
    id: 13,
    name: "Zinfandel",
    brand: "7 Deadly Zins",
    type: "Red",
    color: "Red",
    grapeOrigin: "California",
    sweetness: "Dry",
    locationPurchased: "Binny's",
    price: 11.99,
    year: 2021,
    labelPhoto: "",
    dateAdded: "2025-03-18T13:40:00Z",
    tastings: [],
  },
  {
    id: 14,
    name: "Gewürztraminer",
    brand: "Trimbach",
    type: "White",
    color: "White",
    grapeOrigin: "France",
    sweetness: "Semi-Sweet",
    locationPurchased: "Trader Joe's",
    price: 19.99,
    year: 2020,
    labelPhoto: "",
    dateAdded: "2025-03-19T14:50:00Z",
    tastings: [],
  },
  {
    id: 15,
    name: "Cabernet Sauvignon",
    brand: "Josh Cellars",
    type: "Red",
    color: "Red",
    grapeOrigin: "California",
    sweetness: "Dry",
    locationPurchased: "Costco",
    price: 17.99,
    year: 2021,
    labelPhoto: "",
    dateAdded: "2025-03-20T17:05:00Z",
    tastings: [],
  },
  {
    id: 16,
    name: "Malbec",
    brand: "Catena",
    type: "Red",
    color: "Red",
    grapeOrigin: "Argentina",
    sweetness: "Dry",
    locationPurchased: "Whole Foods",
    price: 15.99,
    year: 2022,
    labelPhoto: "",
    dateAdded: "2025-03-21T11:30:00Z",
    tastings: [],
  },
  {
    id: 17,
    name: "Sangiovese",
    brand: "Antinori",
    type: "Red",
    color: "Red",
    grapeOrigin: "Italy",
    sweetness: "Dry",
    locationPurchased: "Binny's",
    price: 22.99,
    year: 2021,
    labelPhoto: "",
    dateAdded: "2025-03-22T13:15:00Z",
    tastings: [],
  },
  {
    id: 18,
    name: "Pinot Grigio",
    brand: "Santa Margherita",
    type: "White",
    color: "White",
    grapeOrigin: "Italy",
    sweetness: "Dry",
    locationPurchased: "Target",
    price: 20.99,
    year: 2022,
    labelPhoto: "",
    dateAdded: "2025-03-23T09:50:00Z",
    tastings: [],
  },
  {
    id: 19,
    name: "Port",
    brand: "Taylor Fladgate",
    type: "Dessert",
    color: "Dessert",
    grapeOrigin: "Portugal",
    sweetness: "Sweet",
    locationPurchased: "Binny's",
    price: 29.99,
    year: 2018,
    labelPhoto: "",
    dateAdded: "2025-03-24T15:00:00Z",
    tastings: [],
  },
  {
    id: 20,
    name: "Champagne",
    brand: "Veuve Clicquot",
    type: "Sparkling",
    color: "Sparkling",
    grapeOrigin: "France",
    sweetness: "Dry",
    locationPurchased: "Whole Foods",
    price: 49.99,
    year: 2020,
    labelPhoto: "",
    dateAdded: "2025-03-25T12:35:00Z",
    tastings: [],
  },
];

export default WineData;