import placeHolder from "../../../assets/images/emptyWine.jpeg";
const WineData = [
  {
    id: 1,
    color: "Red",
    wineType: "Syrah",
    wineBrand: "Two Buck Chuck",
    year: 2024,
    price: 3.99,
    locationPurchased: "Grocery Store",
    locationName: "Jewel",
    sweetness: "Dry",
    grapeOrigin: "California",
    wineLabelPhoto: placeHolder,
    dateAdded: "2025-03-15T12:00:00Z",
    tastings: []
  },
  {
    id: 2,
    color: "White",
    wineType: "Chardonnay",
    wineBrand: "Barefoot",
    year: 2022,
    price: 5.99,
    locationPurchased: "Beverage Store",
    locationName: "Total Wine",
    sweetness: "Semi-Dry",
    grapeOrigin: "California",
    wineLabelPhoto: placeHolder,
    dateAdded: "2025-03-12T12:00:00Z",
    tastings: []
  },
  {
    id: 3,
    color: "Rosé",
    wineType: "Grenache",
    wineBrand: "Cupcake Vineyards",
    year: 2023,
    price: 8.99,
    locationPurchased: "Winery",
    locationName: "Napa Valley Winery",
    sweetness: "Sweet",
    grapeOrigin: "France",
    wineLabelPhoto: placeHolder,
    dateAdded: "2025-03-10T12:00:00Z",
    tastings: []
  },
  {
    id: 4,
    color: "Red",
    wineType: "Merlot",
    wineBrand: "Black Box",
    year: 2021,
    price: 12.99,
    locationPurchased: "Grocery Store",
    locationName: "Target",
    sweetness: "Dry",
    grapeOrigin: "Washington",
    wineLabelPhoto: placeHolder,
    dateAdded: "2025-03-08T12:00:00Z",
    tastings: []
  },
  {
    id: 5,
    color: "White",
    wineType: "Sauvignon Blanc",
    wineBrand: "Kim Crawford",
    year: 2022,
    price: 11.99,
    locationPurchased: "Beverage Store",
    locationName: "BevMo",
    sweetness: "Dry",
    grapeOrigin: "New Zealand",
    wineLabelPhoto: placeHolder,
    dateAdded: "2025-03-05T12:00:00Z",
    tastings: []
  },
  {
    id: 6,
    color: "Red",
    wineType: "Cabernet Sauvignon",
    wineBrand: "Robert Mondavi",
    year: 2021,
    price: 19.99,
    locationPurchased: "Winery",
    locationName: "Robert Mondavi Winery",
    sweetness: "Dry",
    grapeOrigin: "California",
    wineLabelPhoto: placeHolder,
    dateAdded: "2025-03-02T12:00:00Z",
    tastings: []
  },
  {
    id: 7,
    color: "Red",
    wineType: "Zinfandel",
    wineBrand: "Beringer",
    year: 2020,
    price: 10.49,
    locationPurchased: "Grocery Store",
    locationName: "Costco",
    sweetness: "Semi-Dry",
    grapeOrigin: "California",
    wineLabelPhoto: placeHolder,
    dateAdded: "2025-03-01T12:00:00Z",
    tastings: []
  },
  {
    id: 8,
    color: "White",
    wineType: "Pinot Grigio",
    wineBrand: "Ruffino",
    year: 2021,
    price: 7.99,
    locationPurchased: "Beverage Store",
    locationName: "Walmart",
    sweetness: "Semi-Dry",
    grapeOrigin: "Italy",
    wineLabelPhoto: placeHolder,
    dateAdded: "2025-02-28T12:00:00Z",
    tastings: []
  },
  {
    id: 9,
    color: "Rosé",
    wineType: "Pinot Noir",
    wineBrand: "A to Z Wineworks",
    year: 2022,
    price: 14.99,
    locationPurchased: "Winery",
    locationName: "Oregon Winery",
    sweetness: "Semi-Dry",
    grapeOrigin: "Oregon",
    wineLabelPhoto: placeHolder,
    dateAdded: "2025-02-25T12:00:00Z",
    tastings: []
  },
  {
    id: 10,
    color: "Red",
    wineType: "Malbec",
    wineBrand: "Alamos",
    year: 2021,
    price: 8.99,
    locationPurchased: "Grocery Store",
    locationName: "Safeway",
    sweetness: "Dry",
    grapeOrigin: "Argentina",
    wineLabelPhoto: placeHolder,
    dateAdded: "2025-02-22T12:00:00Z",
    tastings: []
  },
  {
    id: 11,
    color: "White",
    wineType: "Riesling",
    wineBrand: "Chateau Ste. Michelle",
    year: 2023,
    price: 9.99,
    locationPurchased: "Grocery Store",
    locationName: "Ralphs",
    sweetness: "Sweet",
    grapeOrigin: "Washington",
    wineLabelPhoto: placeHolder,
    dateAdded: "2025-02-19T12:00:00Z",
    tastings: []
  },
  {
    id: 12,
    color: "Red",
    wineType: "Pinot Noir",
    wineBrand: "La Crema",
    year: 2022,
    price: 21.99,
    locationPurchased: "Winery",
    locationName: "Sonoma County",
    sweetness: "Dry",
    grapeOrigin: "California",
    wineLabelPhoto: placeHolder,
    dateAdded: "2025-02-16T12:00:00Z",
    tastings: []
  },
  {
    id: 13,
    color: "Red",
    wineType: "Shiraz",
    wineBrand: "Yellow Tail",
    year: 2020,
    price: 6.99,
    locationPurchased: "Grocery Store",
    locationName: "CVS",
    sweetness: "Dry",
    grapeOrigin: "Australia",
    wineLabelPhoto: placeHolder,
    dateAdded: "2025-02-14T12:00:00Z",
    tastings: []
  },
  {
    id: 14,
    color: "White",
    wineType: "Moscato",
    wineBrand: "Barefoot",
    year: 2022,
    price: 5.99,
    locationPurchased: "Grocery Store",
    locationName: "7-Eleven",
    sweetness: "Sweet",
    grapeOrigin: "California",
    wineLabelPhoto: placeHolder,
    dateAdded: "2025-02-11T12:00:00Z",
    tastings: []
  },
  {
    id: 15,
    color: "Red",
    wineType: "Merlot",
    wineBrand: "Woodbridge by Robert Mondavi",
    year: 2021,
    price: 7.99,
    locationPurchased: "Grocery Store",
    locationName: "Kroger",
    sweetness: "Dry",
    grapeOrigin: "California",
    wineLabelPhoto: placeHolder,
    dateAdded: "2025-02-08T12:00:00Z",
    tastings: []
  },
  {
    id: 16,
    color: "White",
    wineType: "Sauvignon Blanc",
    wineBrand: "Cloudy Bay",
    year: 2022,
    price: 24.99,
    locationPurchased: "Winery",
    locationName: "Marlborough",
    sweetness: "Dry",
    grapeOrigin: "New Zealand",
    wineLabelPhoto: placeHolder,
    dateAdded: "2025-02-05T12:00:00Z",
    tastings: []
  },
  {
    id: 17,
    color: "Red",
    wineType: "Tempranillo",
    wineBrand: "Marques de Caceres",
    year: 2020,
    price: 11.99,
    locationPurchased: "Beverage Store",
    locationName: "BevMo",
    sweetness: "Semi-Dry",
    grapeOrigin: "Spain",
    wineLabelPhoto: placeHolder,
    dateAdded: "2025-02-02T12:00:00Z",
    tastings: []
  },
  {
    id: 18,
    color: "Red",
    wineType: "Pinot Noir",
    wineBrand: "E. Guigal",
    year: 2021,
    price: 13.99,
    locationPurchased: "Winery",
    locationName: "Rhône Valley",
    sweetness: "Dry",
    grapeOrigin: "France",
    wineLabelPhoto: placeHolder,
    dateAdded: "2025-01-30T12:00:00Z",
    tastings: []
  },
  {
    id: 19,
    color: "White",
    wineType: "Chardonnay",
    wineBrand: "Coppola",
    year: 2022,
    price: 16.99,
    locationPurchased: "Grocery Store",
    locationName: "Trader Joe's",
    sweetness: "Dry",
    grapeOrigin: "California",
    wineLabelPhoto: placeHolder,
    dateAdded: "2025-01-28T12:00:00Z",
    tastings: []
  },
  {
    id: 20,
    color: "Red",
    wineType: "Cabernet Sauvignon",
    wineBrand: "Silver Oak",
    year: 2020,
    price: 79.99,
    locationPurchased: "Winery",
    locationName: "Napa Valley",
    sweetness: "Dry",
    grapeOrigin: "California",
    wineLabelPhoto: placeHolder,
    dateAdded: "2025-01-25T12:00:00Z",
    tastings: []
  }
];


export default WineData;
